-- ================================================================================================
-- SCRIPT DE MIGRATION INITIAL - CREATION COMPLETE DE LA BASE DE DONNEES
-- ================================================================================================
-- Ce script crée toutes les tables de l'application comme si on partait de zéro
-- Basé sur les entités existantes dans le domain/model
-- Version: 1.0.0
-- Date: 2025-12-27
-- ================================================================================================

-- ================================================================================================
-- 1. TABLES DE REFERENCE (ENUMS ET LOOKUPS)
-- ================================================================================================

-- Table des régions
CREATE TABLE regions (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(10) NOT NULL UNIQUE,
    nom VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500),
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

-- Table des secteurs
CREATE TABLE secteurs (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(10) NOT NULL UNIQUE,
    nom VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500),
    actif BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

-- ================================================================================================
-- 2. TABLE PRINCIPALE USERS
-- ================================================================================================

-- Table des utilisateurs
CREATE TABLE users (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    phone_number VARCHAR(20),
    keycloak_id VARCHAR(100) UNIQUE,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    email_verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMP,
    date_derniere_formation TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0
);

-- Table des rôles utilisateurs (collection table)
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL,
    role VARCHAR(50) NOT NULL,
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_user_role UNIQUE (user_id, role)
);

-- ================================================================================================
-- 3. TABLES METIER - FORMATIONS
-- ================================================================================================

-- Table des formations
CREATE TABLE formations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    libelle VARCHAR(200) NOT NULL,
    formateurs VARCHAR(500) NOT NULL,
    description TEXT,
    date_formation DATE NOT NULL,
    heure_debut TIME NOT NULL,
    heure_fin TIME NOT NULL,
    secteur_id BIGINT NOT NULL,
    region_id BIGINT NOT NULL,
    modalite VARCHAR(20) NOT NULL, -- PRESENTIEL, EN_LIGNE
    nb_participants INTEGER NOT NULL,
    lieu VARCHAR(200),
    ville VARCHAR(100),
    lien_participation VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_formations_secteur FOREIGN KEY (secteur_id) REFERENCES secteurs(id),
    CONSTRAINT fk_formations_region FOREIGN KEY (region_id) REFERENCES regions(id),
    CONSTRAINT chk_formations_modalite CHECK (modalite IN ('PRESENTIEL', 'EN_LIGNE')),
    CONSTRAINT chk_formations_nb_participants CHECK (nb_participants > 0),
    CONSTRAINT chk_formations_heures CHECK (heure_fin > heure_debut)
);

-- Table des participations aux formations
CREATE TABLE formation_participations (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    formation_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    statut_participation VARCHAR(20) NOT NULL DEFAULT 'ABSENT', -- ABSENT, PRESENT
    date_inscription TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_presence TIMESTAMP,
    commentaire VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_formation_participations_formation FOREIGN KEY (formation_id) REFERENCES formations(id) ON DELETE CASCADE,
    CONSTRAINT fk_formation_participations_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_formation_user UNIQUE (formation_id, user_id),
    CONSTRAINT chk_participation_statut CHECK (statut_participation IN ('ABSENT', 'PRESENT'))
);

-- ================================================================================================
-- 4. TABLES BATCH IMPORT
-- ================================================================================================

-- Table des imports batch
CREATE TABLE batch_imports (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    file_name VARCHAR(255) NOT NULL,
    file_size BIGINT,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING', -- PENDING, PROCESSING, COMPLETED, COMPLETED_WITH_ERRORS, FAILED, CANCELLED
    total_lines INTEGER NOT NULL DEFAULT 0,
    processed_lines INTEGER NOT NULL DEFAULT 0,
    success_lines INTEGER NOT NULL DEFAULT 0,
    failed_lines INTEGER NOT NULL DEFAULT 0,
    error_message TEXT,
    initiated_by_user_id BIGINT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_batch_imports_user FOREIGN KEY (initiated_by_user_id) REFERENCES users(id),
    CONSTRAINT chk_batch_import_status CHECK (status IN ('PENDING', 'PROCESSING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'FAILED', 'CANCELLED'))
);

-- Table des lignes d'import batch
CREATE TABLE batch_import_lines (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    batch_import_id BIGINT NOT NULL,
    line_number INTEGER NOT NULL,
    raw_data TEXT,
    success BOOLEAN NOT NULL DEFAULT FALSE,
    error_message TEXT,
    created_user_id BIGINT,

    CONSTRAINT fk_batch_import_lines_batch FOREIGN KEY (batch_import_id) REFERENCES batch_imports(id) ON DELETE CASCADE,
    CONSTRAINT fk_batch_import_lines_user FOREIGN KEY (created_user_id) REFERENCES users(id)
);

-- ================================================================================================
-- 5. TABLES AUDIT (CQRS)
-- ================================================================================================

-- Table des événements d'audit (Command side)
CREATE TABLE audit_event_commands (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_type VARCHAR(50) NOT NULL,
    user_id BIGINT,
    username VARCHAR(50),
    target_entity_type VARCHAR(100),
    target_entity_id VARCHAR(255),
    ip_address VARCHAR(45),
    user_agent VARCHAR(500),
    details TEXT,
    success BOOLEAN NOT NULL DEFAULT TRUE,
    error_message TEXT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Table des projections d'audit (Query side)
CREATE TABLE audit_event_projections (
    id BIGINT PRIMARY KEY,
    event_type VARCHAR(50) NOT NULL,
    event_category VARCHAR(50),
    user_id BIGINT,
    username VARCHAR(50),
    target_entity_type VARCHAR(100),
    target_entity_id VARCHAR(255),
    target_entity_name VARCHAR(200),
    ip_address VARCHAR(45),
    user_agent VARCHAR(500),
    details TEXT,
    success BOOLEAN NOT NULL,
    error_message TEXT,
    timestamp TIMESTAMP NOT NULL,
    event_date DATE,
    event_hour INTEGER
);

-- ================================================================================================
-- 6. INDEX DE PERFORMANCE
-- ================================================================================================

-- Index sur users
CREATE INDEX idx_user_email ON users(email);
CREATE INDEX idx_user_username ON users(username);
CREATE INDEX idx_user_keycloak_id ON users(keycloak_id);
CREATE INDEX idx_user_active ON users(active);
CREATE INDEX idx_user_created_at ON users(created_at);

-- Index sur regions
CREATE INDEX idx_region_nom ON regions(nom);
CREATE INDEX idx_region_code ON regions(code);
CREATE INDEX idx_region_actif ON regions(actif);

-- Index sur secteurs
CREATE INDEX idx_secteur_nom ON secteurs(nom);
CREATE INDEX idx_secteur_code ON secteurs(code);
CREATE INDEX idx_secteur_actif ON secteurs(actif);

-- Index sur formations
CREATE INDEX idx_formation_secteur ON formations(secteur_id);
CREATE INDEX idx_formation_region ON formations(region_id);
CREATE INDEX idx_formation_modalite ON formations(modalite);
CREATE INDEX idx_formation_date_heure ON formations(date_formation, heure_debut, heure_fin);

-- Index sur formation_participations
CREATE INDEX idx_formation_participation_formation ON formation_participations(formation_id);
CREATE INDEX idx_formation_participation_user ON formation_participations(user_id);
CREATE INDEX idx_formation_participation_statut ON formation_participations(statut_participation);
CREATE INDEX idx_formation_participation_formation_statut ON formation_participations(formation_id, statut_participation);

-- Index sur batch_imports
CREATE INDEX idx_batch_imports_status ON batch_imports(status);
CREATE INDEX idx_batch_imports_user ON batch_imports(initiated_by_user_id);
CREATE INDEX idx_batch_imports_created_at ON batch_imports(created_at);

-- Index sur batch_import_lines
CREATE INDEX idx_batch_import_lines_batch ON batch_import_lines(batch_import_id);
CREATE INDEX idx_batch_import_lines_success ON batch_import_lines(success);

-- Index sur audit
CREATE INDEX idx_audit_commands_event_type ON audit_event_commands(event_type, timestamp);
CREATE INDEX idx_audit_commands_timestamp ON audit_event_commands(timestamp);
CREATE INDEX idx_audit_commands_user ON audit_event_commands(user_id);
CREATE INDEX idx_audit_commands_target_entity ON audit_event_commands(target_entity_type, target_entity_id);
CREATE INDEX idx_audit_commands_success ON audit_event_commands(success, timestamp);

CREATE INDEX idx_audit_projections_event_type ON audit_event_projections(event_type, timestamp);
CREATE INDEX idx_audit_projections_timestamp ON audit_event_projections(timestamp);
CREATE INDEX idx_audit_projections_user ON audit_event_projections(user_id);
CREATE INDEX idx_audit_projections_target_entity ON audit_event_projections(target_entity_type, target_entity_id);
CREATE INDEX idx_audit_projections_success ON audit_event_projections(success, timestamp);
CREATE INDEX idx_audit_projections_event_date ON audit_event_projections(event_date);

-- ================================================================================================
-- 7. COMMENTAIRES POUR DOCUMENTATION
-- ================================================================================================

-- Commentaires sur les tables principales
COMMENT ON TABLE users IS 'Table des utilisateurs de l''application avec authentification et profil';
COMMENT ON TABLE user_roles IS 'Table de liaison pour les rôles utilisateurs (relation many-to-many)';
COMMENT ON TABLE regions IS 'Table de référence des régions';
COMMENT ON TABLE secteurs IS 'Table de référence des secteurs d''activité';
COMMENT ON TABLE formations IS 'Table des formations organisées';
COMMENT ON TABLE formation_participations IS 'Table des participations aux formations';
COMMENT ON TABLE batch_imports IS 'Table de suivi des imports en lot';
COMMENT ON TABLE batch_import_lines IS 'Table de détail des lignes d''import en lot';
COMMENT ON TABLE audit_event_commands IS 'Table des événements d''audit côté commande (CQRS)';
COMMENT ON TABLE audit_event_projections IS 'Table des projections d''audit côté requête (CQRS)';

-- Commentaires sur les colonnes critiques
COMMENT ON COLUMN users.id IS 'Identifiant unique de l''utilisateur (BIGINT auto-increment)';
COMMENT ON COLUMN users.keycloak_id IS 'Identifiant Keycloak pour l''intégration OAuth2';
COMMENT ON COLUMN users.date_derniere_formation IS 'Date de la dernière formation suivie avec présence';
COMMENT ON COLUMN formations.modalite IS 'Mode de formation : PRESENTIEL ou EN_LIGNE';
COMMENT ON COLUMN formations.nb_participants IS 'Nombre maximum de participants autorisés';
COMMENT ON COLUMN formation_participations.statut_participation IS 'Statut de participation : ABSENT ou PRESENT';

-- ================================================================================================
-- 8. DONNEES DE REFERENCE INITIALES
-- ================================================================================================

-- Insertion de quelques régions de base
INSERT INTO regions (code, nom, description) VALUES
('IDF', 'Île-de-France', 'Région parisienne'),
('PACA', 'Provence-Alpes-Côte d''Azur', 'Région Sud-Est'),
('ARA', 'Auvergne-Rhône-Alpes', 'Région Centre-Est'),
('NAQ', 'Nouvelle-Aquitaine', 'Région Sud-Ouest'),
('OCC', 'Occitanie', 'Région Languedoc-Roussillon Midi-Pyrénées');

-- Insertion de quelques secteurs de base
INSERT INTO secteurs (code, nom, description) VALUES
('IT', 'Informatique', 'Technologies de l''information'),
('RH', 'Ressources Humaines', 'Gestion des ressources humaines'),
('FIN', 'Finance', 'Secteur financier et comptabilité'),
('COMM', 'Commercial', 'Activités commerciales et vente'),
('PROD', 'Production', 'Activités de production et manufacturing');

-- ================================================================================================
-- FIN DU SCRIPT DE MIGRATION INITIAL
-- ================================================================================================